pipeline {
    agent any

    parameters {
        choice(name: 'APPROVAL', choices: ['Abort', 'Deploy'], description: 'QA approval required')
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t feedback-app .'
            }
        }

        stage('Test') {
            steps {
                echo 'Running dummy tests...'
                sh './test/dummy-test.sh'
            }
        }

        stage('Deploy') {
            when {
                expression { params.APPROVAL == 'Deploy' }
            }
            steps {
                echo 'Stopping old container if exists...'
                sh 'docker rm -f feedback-app-container || true'
                
                echo 'Deploying new container...'
                sh 'docker run -d --name feedback-app-container -p 8080:80 feedback-app'
            }
        }
    }
}
